language: rust
rust:
  - nightly
os: linux
dist: xenial

sudo: required

matrix:
  allow_failures:
    - rust: nightly

addons:
  apt:
    packages:
      - libssl-dev

env:
  global:
    - PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/
    - LD_LIBRARY_PATH=/usr/local/lib/

before_install:
  - sudo bash ./fast-install.sh

before_cache:
  - RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin -f

script:
  - cd ./app
  - cargo test

after_success: |
  cargo tarpaulin --out Xml
  sudo bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

notifications:
  email:
    - mr.amirka@ya.ru
  slack:
    on_success: always
    on_failure: always
