language: rust
rust:
  - nightly
os: linux
dist: xenial

cache: cargo

sudo: required

env:
  global:
    - PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/
    - LD_LIBRARY_PATH=/usr/local/lib/

before_install:
  - sudo bash ./fast-install.sh
  - sudo bash ./kcov-install.sh

script:
  # Запуск тестов
  - cd ./app && cargo test
  - cd ..
  - sudo kcov --exclude-pattern=/.cargo,/usr/lib --verify ./app/target/cov ./app/target/debug/tr_logic_llc-*

notifications:
  email:
    - mr.amirka@ya.ru
  slack:
    on_success: always
    on_failure: always
