language: rust
rust:
  - nightly
os: linux
dist: xenial

sudo: required

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev

matrix:
  allow_failures:
    - rust: nightly

env:
  global:
    - PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/
    - LD_LIBRARY_PATH=/usr/local/lib/

before_install:
  - sudo bash ./fast-install.sh

before_cache:
  - cargo install cargo-tarpaulin -f

script:
  - cargo test

after_success: |
  cargo tarpaulin --out Xml
  bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN


notifications:
  email:
    - mr.amirka@ya.ru
  slack:
    on_success: always
    on_failure: always
