FROM rust:latest

# Папка приложения
ARG APP_DIR=/home/tr_logic_llc
RUN mkdir -p ${APP_DIR}
WORKDIR ${APP_DIR}

RUN rustup install nightly && rustup default nightly

COPY ./fast-install.sh ./fast-install.sh
RUN bash ./fast-install.sh && rm -rf ./fast-install.sh
RUN ldconfig
RUN export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/
RUN export LD_LIBRARY_PATH=/usr/local/lib/
